// Source configuration: tiers + RSS feed URLs.
// TIER1 = highest reliability, TIER4 = lowest. Add/remove sources here only.
//
// This list is built from the user-supplied source directory. Only entries
// with a publicly documented RSS/Atom feed URL are included below, since the
// fetcher (netlify/functions/news.js) parses RSS/Atom — a homepage URL alone
// cannot be polled for structured articles. Many outlets in the supplied
// directory (e.g. most non-English regional papers, government/trade bodies
// such as WTO, UNCTAD, JETRO, KOTRA, MOFCOM) do not publish a public RSS feed
// and are intentionally left out to avoid guessing non-existent URLs; add
// them here once you have their real feed endpoint (see README "Adding a
// News Source"). The homepage for every supplied outlet is kept in
// SOURCE_DIRECTORY below for reference even where no feed is wired up yet.
const SOURCES = [
  // --- Tier 1: wire services / top-tier global business press ---
  // Reuters and AP retired their old public RSS endpoints; scoped Google News
  // RSS queries (site: + commercial keywords) are used instead. This is a
  // legitimate public RSS mechanism (no scraping/bypass) and, as a bonus,
  // narrows results to marketing/trade/sales topics rather than all general
  // and political news from these outlets.
  { id: "reuters-trade", name: "Reuters", tier: 1, url: "https://news.google.com/rss/search?q=site:reuters.com+(marketing+OR+trade+OR+tariff+OR+export+OR+import+OR+sales+OR+advertising)+when:2d&hl=en-US&gl=US&ceid=US:en" },
  { id: "ap-trade", name: "Associated Press", tier: 1, url: "https://news.google.com/rss/search?q=site:apnews.com+(marketing+OR+trade+OR+tariff+OR+export+OR+import+OR+sales+OR+retail)+when:2d&hl=en-US&gl=US&ceid=US:en" },
  { id: "bbc-business", name: "BBC Business", tier: 1, url: "http://feeds.bbci.co.uk/news/business/rss.xml" },
  { id: "ft", name: "Financial Times", tier: 1, url: "https://www.ft.com/rss/home" },
  { id: "guardian-business", name: "The Guardian Business", tier: 1, url: "https://www.theguardian.com/business/rss" },
  { id: "nikkei-asia", name: "Nikkei Asia", tier: 1, url: "https://asia.nikkei.com/rss/feed/nar" },

  // --- Tier 2: reputable business / specialist press ---
  { id: "cnbc-world", name: "CNBC", tier: 2, url: "https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=100727362" },
  { id: "marketwatch", name: "MarketWatch", tier: 2, url: "http://feeds.marketwatch.com/marketwatch/topstories/" },
  { id: "forbes-cmo", name: "Forbes", tier: 2, url: "https://www.forbes.com/marketing/feed/" },
  { id: "fortune", name: "Fortune", tier: 2, url: "https://fortune.com/feed/" },
  { id: "business-insider", name: "Business Insider", tier: 2, url: "https://www.businessinsider.com/rss" },
  { id: "axios", name: "Axios", tier: 2, url: "https://api.axios.com/feed/" },
  { id: "politico-trade", name: "POLITICO", tier: 2, url: "https://rss.politico.com/economy.xml" },
  { id: "fastcompany", name: "Fast Company", tier: 2, url: "https://www.fastcompany.com/rss.xml" },
  { id: "inc", name: "Inc.", tier: 2, url: "https://www.inc.com/rss" },
  { id: "entrepreneur", name: "Entrepreneur", tier: 2, url: "https://www.entrepreneur.com/latest.rss" },
  { id: "nytimes-business", name: "The New York Times", tier: 2, url: "https://rss.nytimes.com/services/xml/rss/nyt/Business.xml" },
  { id: "scmp", name: "South China Morning Post", tier: 2, url: "https://www.scmp.com/rss/91/feed" },
  { id: "koreaherald", name: "The Korea Herald", tier: 2, url: "http://www.koreaherald.com/rss/020000000000.xml" },
  { id: "japantimes", name: "The Japan Times", tier: 2, url: "https://www.japantimes.co.jp/news_category/business/feed/" },
  { id: "straitstimes-business", name: "The Straits Times", tier: 2, url: "https://news.google.com/rss/search?q=site:straitstimes.com+business+when:2d&hl=en-US&gl=US&ceid=US:en" },
  { id: "economictimes", name: "The Economic Times", tier: 2, url: "https://news.google.com/rss/search?q=site:economictimes.indiatimes.com+(marketing+OR+trade+OR+retail+OR+export)+when:2d&hl=en-US&gl=US&ceid=US:en" },
  { id: "businesstoday-india", name: "Business Today India", tier: 2, url: "https://www.businesstoday.in/rssfeeds/?id=225346" },
  { id: "moneycontrol", name: "Moneycontrol", tier: 2, url: "https://www.moneycontrol.com/rss/business.xml" },
  { id: "arabianbusiness", name: "Arabian Business", tier: 2, url: "https://www.arabianbusiness.com/feed" },
  { id: "gulfbusiness", name: "Gulf Business", tier: 2, url: "https://news.google.com/rss/search?q=site:gulfbusiness.com+when:3d&hl=en-US&gl=US&ceid=US:en" },
  { id: "khaleejtimes-business", name: "Khaleej Times", tier: 2, url: "https://www.khaleejtimes.com/business?rss=true" },
  { id: "globalnews-ca-business", name: "The Globe and Mail", tier: 2, url: "https://news.google.com/rss/search?q=site:theglobeandmail.com+business+(trade+OR+marketing+OR+retail+OR+export)+when:2d&hl=en-US&gl=US&ceid=US:en" },
  { id: "afr", name: "Australian Financial Review", tier: 2, url: "https://news.google.com/rss/search?q=site:afr.com+when:2d&hl=en-US&gl=US&ceid=US:en" },
  { id: "smh-business", name: "Sydney Morning Herald", tier: 2, url: "https://www.smh.com.au/rss/business.xml" },

  // --- Tier 3: established industry / specialist marketing, sales & trade press ---
  // (dedicated marketing/sales titles, weighted more heavily than general
  // newspapers, so commercial content isn't drowned out by macro/political
  // coverage from the broad business press above)
  { id: "adage", name: "Ad Age", tier: 3, url: "https://news.google.com/rss/search?q=site:adage.com+when:2d&hl=en-US&gl=US&ceid=US:en" },
  { id: "adweek", name: "Adweek", tier: 3, url: "https://www.adweek.com/feed/" },
  { id: "marketingdive", name: "Marketing Dive", tier: 3, url: "https://www.marketingdive.com/feeds/news/" },
  { id: "digiday", name: "Digiday", tier: 3, url: "https://digiday.com/feed/" },
  { id: "mediapost", name: "MediaPost", tier: 3, url: "https://news.google.com/rss/search?q=site:mediapost.com+when:2d&hl=en-US&gl=US&ceid=US:en" },
  { id: "searchenginejournal", name: "Search Engine Journal", tier: 3, url: "https://www.searchenginejournal.com/feed/" },
  { id: "searchengineland", name: "Search Engine Land", tier: 3, url: "https://news.google.com/rss/search?q=site:searchengineland.com+when:3d&hl=en-US&gl=US&ceid=US:en" },
  { id: "retaildive", name: "Retail Dive", tier: 3, url: "https://www.retaildive.com/feeds/news/" },
  { id: "prweek", name: "PRWeek", tier: 3, url: "https://news.google.com/rss/search?q=site:prweek.com+when:3d&hl=en-US&gl=US&ceid=US:en" },
  { id: "socialmediatoday", name: "Social Media Today", tier: 3, url: "https://www.socialmediatoday.com/feeds/news/" },
  { id: "thedrum", name: "The Drum", tier: 3, url: "https://news.google.com/rss/search?q=site:thedrum.com+when:2d&hl=en-US&gl=US&ceid=US:en" },
  { id: "hubspot-sales", name: "HubSpot Sales Blog", tier: 3, url: "https://blog.hubspot.com/sales/rss.xml" },
  { id: "supplychaindive", name: "Supply Chain Dive", tier: 3, url: "https://www.supplychaindive.com/feeds/news/" },
  { id: "freightwaves", name: "FreightWaves", tier: 3, url: "https://www.freightwaves.com/news/feed" },
  { id: "joc", name: "Journal of Commerce", tier: 3, url: "https://www.joc.com/rss.xml" },
  { id: "logisticsmgmt", name: "Logistics Management", tier: 3, url: "https://news.google.com/rss/search?q=site:logisticsmgmt.com+when:3d&hl=en-US&gl=US&ceid=US:en" },
  { id: "inboundlogistics", name: "Inbound Logistics", tier: 3, url: "https://news.google.com/rss/search?q=site:inboundlogistics.com+when:3d&hl=en-US&gl=US&ceid=US:en" },
  { id: "theloadstar", name: "The Loadstar", tier: 3, url: "https://theloadstar.com/feed/" },
  { id: "marketingweek", name: "Marketing Week", tier: 3, url: "https://news.google.com/rss/search?q=site:marketingweek.com+when:2d&hl=en-US&gl=US&ceid=US:en" },
  { id: "campaignlive-uk", name: "Campaign UK", tier: 3, url: "https://news.google.com/rss/search?q=site:campaignlive.co.uk+when:2d&hl=en-US&gl=US&ceid=US:en" },

  // --- Additional dedicated marketing/sales/e-commerce titles, added to
  // increase commercial-content share relative to general/political news ---
  { id: "thinkwithgoogle", name: "Think with Google", tier: 3, url: "https://www.thinkwithgoogle.com/feed/intl/en-us/" },
  { id: "emarketer", name: "eMarketer", tier: 3, url: "https://www.emarketer.com/rss/all/" },
  { id: "cmi", name: "Content Marketing Institute", tier: 3, url: "https://contentmarketinginstitute.com/feed/" },
  { id: "chiefmarketer", name: "Chief Marketer", tier: 3, url: "https://www.chiefmarketer.com/feed/" },
  { id: "martech-org", name: "MarTech", tier: 3, url: "https://martech.org/feed/" },
  { id: "salesforce-blog", name: "Salesforce Blog", tier: 3, url: "https://www.salesforce.com/blog/feed/" },
  { id: "nrf-retail", name: "National Retail Federation", tier: 2, url: "https://nrf.com/rss.xml" },
  { id: "internetretailer", name: "Digital Commerce 360", tier: 3, url: "https://www.digitalcommerce360.com/feed/" },
  { id: "warc-news", name: "WARC", tier: 3, url: "https://www.warc.com/rss/newsandopinion" },
  { id: "gtreview", name: "Global Trade Review", tier: 3, url: "https://www.gtreview.com/feed/" },
];

// Reference-only directory of every source supplied by the user, including
// those without a wired-up RSS feed yet. Not used for fetching; kept so the
// homepage/attribution is on record and new feeds are easy to slot in.
const SOURCE_DIRECTORY = {
  "Reuters": "https://www.reuters.com/", "Bloomberg": "https://www.bloomberg.com/",
  "Financial Times": "https://www.ft.com/", "The Wall Street Journal": "https://www.wsj.com/",
  "The Economist": "https://www.economist.com/", "CNBC": "https://www.cnbc.com/",
  "Forbes": "https://www.forbes.com/", "Fortune": "https://fortune.com/",
  "Business Insider": "https://www.businessinsider.com/", "BBC Business": "https://www.bbc.com/business",
  "Associated Press": "https://apnews.com/", "Agence France-Presse": "https://www.afp.com/",
  "Nikkei Asia": "https://asia.nikkei.com/", "S&P Global": "https://www.spglobal.com/",
  "McKinsey": "https://www.mckinsey.com/", "Harvard Business Review": "https://hbr.org/",
  "MIT Sloan Management Review": "https://sloanreview.mit.edu/", "Bain & Company Insights": "https://www.bain.com/insights/",
  "BCG Insights": "https://www.bcg.com/insights", "Strategy+Business": "https://www.strategy-business.com/",
  "Fast Company": "https://www.fastcompany.com/", "Inc.": "https://www.inc.com/",
  "Entrepreneur": "https://www.entrepreneur.com/", "The New York Times": "https://www.nytimes.com/section/business",
  "The Washington Post": "https://www.washingtonpost.com/business/", "USA Today": "https://www.usatoday.com/money/",
  "Investor's Business Daily": "https://www.investors.com/", "Barron's": "https://www.barrons.com/",
  "MarketWatch": "https://www.marketwatch.com/", "American City Business Journals": "https://www.bizjournals.com/",
  "Crain's Chicago Business": "https://www.chicagobusiness.com/", "Ad Age": "https://adage.com/",
  "Adweek": "https://www.adweek.com/", "Marketing Dive": "https://www.marketingdive.com/",
  "Digiday": "https://digiday.com/", "MediaPost": "https://www.mediapost.com/",
  "MarTech": "https://martech.org/", "Search Engine Land": "https://searchengineland.com/",
  "Search Engine Journal": "https://www.searchenginejournal.com/", "Retail Dive": "https://www.retaildive.com/",
  "PRWeek": "https://www.prweek.com/", "Social Media Today": "https://www.socialmediatoday.com/",
  "WARC": "https://www.warc.com/", "Brandweek": "https://www.brandweek.com/",
  "Campaign US": "https://www.campaignlive.com/", "Salesforce": "https://www.salesforce.com/blog/",
  "HubSpot Sales": "https://blog.hubspot.com/sales", "Selling Power": "https://www.sellingpower.com/",
  "Sales Hacker": "https://www.saleshacker.com/", "Gartner": "https://www.gartner.com/en/sales",
  "RAIN Group": "https://www.rainsalestraining.com/", "Sales Management Association": "https://salesmanagement.org/",
  "Cognism": "https://www.cognism.com/blog", "Journal of Commerce": "https://www.joc.com/",
  "FreightWaves": "https://www.freightwaves.com/", "American Shipper": "https://www.americanshipper.com/",
  "Supply Chain Dive": "https://www.supplychaindive.com/", "Logistics Management": "https://www.logisticsmgmt.com/",
  "Inbound Logistics": "https://www.inboundlogistics.com/", "The Loadstar": "https://theloadstar.com/",
  "Global Trade Magazine": "https://www.globaltrademag.com/", "Trade Finance Global": "https://www.tradefinanceglobal.com/",
  "Global Trade Review": "https://www.gtreview.com/", "Inside U.S. Trade": "https://insidetrade.com/",
  "International Trade Today": "https://internationaltradetoday.com/", "The Globe and Mail": "https://www.theglobeandmail.com/",
  "Financial Post": "https://financialpost.com/", "Toronto Star": "https://www.thestar.com/",
  "CBC Business": "https://www.cbc.ca/news/business", "BNN Bloomberg": "https://www.bnnbloomberg.ca/",
  "Canadian Business": "https://www.canadianbusiness.com/", "Investment Executive": "https://www.investmentexecutive.com/",
  "Retail Insider": "https://retail-insider.com/", "Canadian Manufacturing": "https://www.canadianmanufacturing.com/",
  "Australian Financial Review": "https://www.afr.com/", "The Australian": "https://www.theaustralian.com.au/",
  "Sydney Morning Herald": "https://www.smh.com.au/", "The Age": "https://www.theage.com.au/",
  "ABC Business": "https://www.abc.net.au/news/business/", "News.com.au Business": "https://www.news.com.au/finance",
  "SmartCompany": "https://www.smartcompany.com.au/", "Inside Retail Australia": "https://insideretail.com.au/",
  "Business News Australia": "https://www.businessnewsaustralia.com/", "InnovationAus": "https://www.innovationaus.com/",
  "The Times": "https://www.thetimes.com/business", "The Telegraph": "https://www.telegraph.co.uk/business/",
  "The Guardian Business": "https://www.theguardian.com/business", "City A.M.": "https://www.cityam.com/",
  "Sky News Business": "https://news.sky.com/business", "BusinessLive": "https://www.business-live.co.uk/",
  "This Is Money": "https://www.thisismoney.co.uk/", "Marketing Week": "https://www.marketingweek.com/",
  "Campaign UK": "https://www.campaignlive.co.uk/", "The Drum": "https://www.thedrum.com/",
  "PRWeek UK": "https://www.prweek.com/", "MarketingTechNews": "https://marketingtechnews.net/",
  "Euronews Business": "https://www.euronews.com/business", "POLITICO Europe": "https://www.politico.eu/",
  "EUobserver": "https://euobserver.com/", "European Commission Trade": "https://policy.trade.ec.europa.eu/",
  "European Commission Economy": "https://economy-finance.ec.europa.eu/", "Eurostat": "https://ec.europa.eu/eurostat/",
  "European Central Bank": "https://www.ecb.europa.eu/", "European Parliament": "https://www.europarl.europa.eu/",
  "Handelsblatt": "https://www.handelsblatt.com/", "WirtschaftsWoche": "https://www.wiwo.de/",
  "Börsen-Zeitung": "https://www.boersen-zeitung.de/", "Manager Magazin": "https://www.manager-magazin.de/",
  "Deutsche Welle Business": "https://www.dw.com/en/business/s-1431", "Les Échos": "https://www.lesechos.fr/",
  "La Tribune": "https://www.latribune.fr/", "Le Figaro Économie": "https://www.lefigaro.fr/economie",
  "L'Usine Nouvelle": "https://www.usinenouvelle.com/", "Il Sole 24 Ore": "https://www.ilsole24ore.com/",
  "Milano Finanza": "https://www.milanofinanza.it/", "ItaliaOggi": "https://www.italiaoggi.it/",
  "Expansión": "https://www.expansion.com/", "Cinco Días": "https://cincodias.elpais.com/",
  "El Economista": "https://www.eleconomista.es/", "Het Financieele Dagblad": "https://fd.nl/",
  "De Telegraaf": "https://www.telegraaf.nl/", "De Tijd": "https://www.tijd.be/", "L'Echo": "https://www.lecho.be/",
  "Dagens Industri": "https://www.di.se/", "Børsen": "https://borsen.dk/", "Kauppalehti": "https://www.kauppalehti.fi/",
  "The Irish Times Business": "https://www.irishtimes.com/business/", "Irish Independent Business": "https://www.independent.ie/business/",
  "South China Morning Post": "https://www.scmp.com/", "Caixin Global": "https://www.caixinglobal.com/",
  "China Daily": "https://www.chinadaily.com.cn/business/", "Global Times": "https://www.globaltimes.cn/business/",
  "CGTN Business": "https://news.cgtn.com/business", "China Economic Net": "http://en.ce.cn/",
  "21st Century Business Herald": "https://www.21jingji.com/", "Yicai": "https://www.yicai.com/",
  "Economic Daily China": "http://www.ce.cn/", "Securities Times": "https://www.stcn.com/",
  "China Business Journal": "https://www.cb.com.cn/", "The Korea Herald": "https://www.koreaherald.com/",
  "The Korea Times": "https://www.koreatimes.co.kr/", "Yonhap News": "https://en.yna.co.kr/",
  "Maeil Business Newspaper": "https://www.mk.co.kr/", "Korea Economic Daily": "https://www.kedglobal.com/",
  "The Chosun Ilbo": "https://www.chosun.com/", "JoongAng Daily": "https://koreajoongangdaily.joins.com/",
  "Pulse": "https://pulse.mk.co.kr/", "Nikkei": "https://www.nikkei.com/", "The Japan Times": "https://www.japantimes.co.jp/",
  "Kyodo News": "https://english.kyodonews.net/", "Yomiuri Shimbun": "https://www.yomiuri.co.jp/",
  "The Asahi Shimbun": "https://www.asahi.com/", "The Mainichi": "https://mainichi.jp/english/",
  "Jiji Press": "https://www.jiji.com/", "Japan Today": "https://japantoday.com/",
  "The Business Times Singapore": "https://www.businesstimes.com.sg/", "Channel NewsAsia": "https://www.channelnewsasia.com/business",
  "The Straits Times": "https://www.straitstimes.com/business", "Singapore Business Review": "https://sbr.com.sg/",
  "The Jakarta Post": "https://www.thejakartapost.com/", "Bisnis Indonesia": "https://www.bisnis.com/",
  "Kontan": "https://www.kontan.co.id/", "Investor Daily Indonesia": "https://investor.id/",
  "The Edge Malaysia": "https://theedgemalaysia.com/", "The Star Business": "https://www.thestar.com.my/business",
  "New Straits Times": "https://www.nst.com.my/business", "Bernama": "https://www.bernama.com/",
  "Bangkok Post": "https://www.bangkokpost.com/business", "The Nation Thailand": "https://www.nationthailand.com/business",
  "Thai PBS World": "https://www.thaipbsworld.com/", "Vietnam Investment Review": "https://vir.com.vn/",
  "Vietnam News": "https://vietnamnews.vn/", "VnExpress": "https://e.vnexpress.net/",
  "BusinessWorld Philippines": "https://www.bworldonline.com/", "BusinessMirror": "https://businessmirror.com.ph/",
  "Philippine Daily Inquirer": "https://business.inquirer.net/", "The Economic Times": "https://economictimes.indiatimes.com/",
  "Business Standard": "https://www.business-standard.com/", "Mint": "https://www.livemint.com/",
  "Financial Express": "https://www.financialexpress.com/", "The Hindu BusinessLine": "https://www.thehindubusinessline.com/",
  "Business Today India": "https://www.businesstoday.in/", "Moneycontrol": "https://www.moneycontrol.com/",
  "The Hindu Business": "https://www.thehindu.com/business/", "CNBC-TV18": "https://www.cnbctv18.com/",
  "ET Brand Equity": "https://brandequity.economictimes.indiatimes.com/", "Valor Econômico": "https://valor.globo.com/",
  "O Estado de S. Paulo": "https://www.estadao.com.br/economia/", "Folha de S.Paulo": "https://www1.folha.uol.com.br/mercado/",
  "O Globo": "https://oglobo.globo.com/economia/", "Exame": "https://exame.com/", "InfoMoney": "https://www.infomoney.com.br/",
  "Brazil Journal": "https://braziljournal.com/", "Poder360": "https://www.poder360.com.br/",
  "Agência Brasil": "https://agenciabrasil.ebc.com.br/economia", "RBC": "https://www.rbc.ru/",
  "Kommersant": "https://www.kommersant.ru/", "Vedomosti": "https://www.vedomosti.ru/",
  "Interfax": "https://www.interfax.ru/", "TASS": "https://tass.com/economy",
  "The Moscow Times": "https://www.themoscowtimes.com/", "Rossiyskaya Gazeta": "https://rg.ru/",
  "Expert": "https://expert.ru/", "Arabian Business": "https://www.arabianbusiness.com/",
  "Gulf Business": "https://gulfbusiness.com/", "Zawya": "https://www.zawya.com/",
  "The National": "https://www.thenationalnews.com/business/", "Khaleej Times": "https://www.khaleejtimes.com/business",
  "Gulf News": "https://gulfnews.com/business", "Emirates News Agency (WAM)": "https://www.wam.ae/",
  "Dubai Media Office": "https://mediaoffice.ae/", "Abu Dhabi Media Office": "https://www.mediaoffice.abudhabi/",
  "MEED": "https://www.meed.com/", "Construction Business News ME": "https://www.cbnme.com/",
  "Hotelier Middle East": "https://www.hoteliermiddleeast.com/", "Logistics Middle East": "https://www.logisticsmiddleeast.com/",
  "World Trade Organization": "https://www.wto.org/", "UN Trade and Development (UNCTAD)": "https://unctad.org/",
  "International Trade Centre (ITC)": "https://www.intracen.org/", "World Bank": "https://www.worldbank.org/",
  "International Monetary Fund": "https://www.imf.org/", "OECD": "https://www.oecd.org/",
  "World Customs Organization": "https://www.wcoomd.org/", "Global Trade Alert": "https://globaltradealert.org/",
  "U.S. International Trade Administration": "https://www.trade.gov/", "U.S. International Trade Commission": "https://www.usitc.gov/",
  "U.S. Census Bureau Foreign Trade": "https://www.census.gov/foreign-trade/", "Canada Trade Commissioner Service": "https://www.tradecommissioner.gc.ca/",
  "Austrade": "https://www.austrade.gov.au/", "JETRO": "https://www.jetro.go.jp/en/", "KOTRA": "https://www.kotra.or.kr/",
  "China MOFCOM": "https://english.mofcom.gov.cn/", "India Ministry of Commerce": "https://www.commerce.gov.in/",
  "Brazil MDIC": "https://www.gov.br/mdic/", "UAE Ministry of Economy": "https://www.moec.gov.ae/",
  "UK Department for Business and Trade": "https://www.gov.uk/government/organisations/department-for-business-and-trade",
};
if (typeof module !== "undefined") module.exports = SOURCES;
if (typeof module !== "undefined") module.exports.SOURCE_DIRECTORY = SOURCE_DIRECTORY;
